# Generated by Django 5.2.13 on 2026-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_game_delete_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(upload_to="games/"),
        ),
    ]
